### ISSUE TITLE
Password is stored as plain text and is not hashed

### ISSUE THREAD

**Issue by Calebrw** [mariofont/PHP-Login#1]
My first concern is that the password is stored as plain text with no hashing. Take a look at PHP's [password_hash function](http://php.net/manual/en/function.password-hash.php). While it is true that in theory an end-user should never see the raw PHP, it's certainly possible that something go wrong and then you have the end user's password out for the world to see. Given the fact that humans often re-use passwords, this means a hacker could gain access to other accounts.

**Comment by Calebrw** [comment]
#2 Fixes some of these problems.

**Comment by mariofont** [comment]
Yep, should be fixed now.
